package net.jace007.jacesmegawoodcollection.datagen;

import net.jace007.jacesmegawoodcollection.JacesMegaWoodCollection;
import net.jace007.jacesmegawoodcollection.block.JMWCBlocks;
import net.jace007.jacesmegawoodcollection.util.JMWCTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class JMWCBlockTagProvider extends BlockTagsProvider {
    public JMWCBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, JacesMegaWoodCollection.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(JMWCTags.Blocks.AGRABAH_CEDAR)
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_PLANKS.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_STAIRS.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG_STAIRS.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_SLAB.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG_SLAB.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_FENCE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_FENCE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_FENCE_GATE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_DOOR.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_TRAPDOOR.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_BUTTON.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_PRESSUREPLATE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LEAVES.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_SAPLING.get());

        tag(JMWCTags.Blocks.ALLMEN_OAK)
                .add(JMWCBlocks.ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.ALLMEN_OAK_PLANKS.get())
                .add(JMWCBlocks.ALLMEN_OAK_STAIRS.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.ALLMEN_OAK_SLAB.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.ALLMEN_OAK_FENCE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_FENCE.get())
                .add(JMWCBlocks.ALLMEN_OAK_FENCE_GATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_DOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_TRAPDOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_BUTTON.get())
                .add(JMWCBlocks.ALLMEN_OAK_PRESSUREPLATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LEAVES.get())
                .add(JMWCBlocks.ALLMEN_OAK_SAPLING.get());

        tag(JMWCTags.Blocks.AUDRAFLORA_OAK)
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_PLANKS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_STAIRS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_SLAB.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_FENCE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_FENCE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_FENCE_GATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_DOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_TRAPDOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_BUTTON.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_PRESSUREPLATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LEAVES.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_SAPLING.get());

        tag(JMWCTags.Blocks.BLACK_ABORA)
                .add(JMWCBlocks.BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.BLACK_ABORA_PLANKS.get())
                .add(JMWCBlocks.BLACK_ABORA_STAIRS.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG_STAIRS.get())
                .add(JMWCBlocks.BLACK_ABORA_SLAB.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG_SLAB.get())
                .add(JMWCBlocks.BLACK_ABORA_FENCE.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_FENCE.get())
                .add(JMWCBlocks.BLACK_ABORA_FENCE_GATE.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.BLACK_ABORA_DOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_TRAPDOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_BUTTON.get())
                .add(JMWCBlocks.BLACK_ABORA_PRESSUREPLATE.get())
                .add(JMWCBlocks.BLACK_ABORA_LEAVES.get())
                .add(JMWCBlocks.BLACK_ABORA_SAPLING.get());

        tag(JMWCTags.Blocks.CARAVAN_OLIVEWOOD)
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_WOOD.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_WOOD.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_PLANKS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_STAIRS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG_STAIRS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_SLAB.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG_SLAB.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_FENCE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_FENCE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_FENCE_GATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_DOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_TRAPDOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_BUTTON.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_PRESSUREPLATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LEAVES.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_SAPLING.get());

        tag(JMWCTags.Blocks.AGRABAH_CEDAR_LOGS)
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_WOOD.get());

        tag(JMWCTags.Blocks.ALLMEN_OAK_LOGS)
                .add(JMWCBlocks.ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_WOOD.get());

        tag(JMWCTags.Blocks.AUDRAFLORA_OAK_LOGS)
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_WOOD.get());

        tag(JMWCTags.Blocks.BLACK_ABORA_LOGS)
                .add(JMWCBlocks.BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_WOOD.get());

        tag(JMWCTags.Blocks.CARAVAN_OLIVEWOOD_LOGS)
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_WOOD.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_WOOD.get());

        this.tag(BlockTags.LOGS_THAT_BURN)
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_WOOD.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_WOOD.get());

        tag(BlockTags.MINEABLE_WITH_AXE)
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_PLANKS.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_STAIRS.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG_STAIRS.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_SLAB.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG_SLAB.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_FENCE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_FENCE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_FENCE_GATE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_DOOR.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_TRAPDOOR.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_BUTTON.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_PRESSUREPLATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.ALLMEN_OAK_PLANKS.get())
                .add(JMWCBlocks.ALLMEN_OAK_STAIRS.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.ALLMEN_OAK_SLAB.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.ALLMEN_OAK_FENCE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_FENCE.get())
                .add(JMWCBlocks.ALLMEN_OAK_FENCE_GATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_DOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_TRAPDOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_BUTTON.get())
                .add(JMWCBlocks.ALLMEN_OAK_PRESSUREPLATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_PLANKS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_STAIRS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_SLAB.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_FENCE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_FENCE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_FENCE_GATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_DOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_TRAPDOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_BUTTON.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_PRESSUREPLATE.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.BLACK_ABORA_PLANKS.get())
                .add(JMWCBlocks.BLACK_ABORA_STAIRS.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG_STAIRS.get())
                .add(JMWCBlocks.BLACK_ABORA_SLAB.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG_SLAB.get())
                .add(JMWCBlocks.BLACK_ABORA_FENCE.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_FENCE.get())
                .add(JMWCBlocks.BLACK_ABORA_FENCE_GATE.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.BLACK_ABORA_DOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_TRAPDOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_BUTTON.get())
                .add(JMWCBlocks.BLACK_ABORA_PRESSUREPLATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_WOOD.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_WOOD.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_PLANKS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_STAIRS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG_STAIRS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_SLAB.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG_SLAB.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_FENCE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_FENCE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_FENCE_GATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_DOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_TRAPDOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_BUTTON.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_PRESSUREPLATE.get());

        tag(BlockTags.LOGS)
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_WOOD.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_WOOD.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_WOOD.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_WOOD.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_WOOD.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_WOOD.get());

        tag(BlockTags.BUTTONS)
                .add(JMWCBlocks.AGRABAH_CEDAR_BUTTON.get())
                .add(JMWCBlocks.ALLMEN_OAK_BUTTON.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_BUTTON.get())
                .add(JMWCBlocks.BLACK_ABORA_BUTTON.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_BUTTON.get());

        tag(BlockTags.COMPLETES_FIND_TREE_TUTORIAL)
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG.get());

        tag(BlockTags.DOORS)
                .add(JMWCBlocks.AGRABAH_CEDAR_DOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_DOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_DOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_DOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_DOOR.get());

        tag(BlockTags.FENCE_GATES)
                .add(JMWCBlocks.AGRABAH_CEDAR_FENCE_GATE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_FENCE_GATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_FENCE_GATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.BLACK_ABORA_FENCE_GATE.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_FENCE_GATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_FENCE_GATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_FENCE_GATE.get());

        tag(BlockTags.FENCES)
                .add(JMWCBlocks.AGRABAH_CEDAR_FENCE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_FENCE.get())
                .add(JMWCBlocks.ALLMEN_OAK_FENCE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_FENCE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_FENCE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_FENCE.get())
                .add(JMWCBlocks.BLACK_ABORA_FENCE.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_FENCE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_FENCE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_FENCE.get());

        tag(BlockTags.LEAVES)
                .add(JMWCBlocks.AGRABAH_CEDAR_LEAVES.get())
                .add(JMWCBlocks.ALLMEN_OAK_LEAVES.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LEAVES.get())
                .add(JMWCBlocks.BLACK_ABORA_LEAVES.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LEAVES.get());

        tag(BlockTags.PLANKS)
                .add(JMWCBlocks.AGRABAH_CEDAR_PLANKS.get())
                .add(JMWCBlocks.ALLMEN_OAK_PLANKS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_PLANKS.get())
                .add(JMWCBlocks.BLACK_ABORA_PLANKS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_PLANKS.get());

        tag(BlockTags.PRESSURE_PLATES)
                .add(JMWCBlocks.AGRABAH_CEDAR_PRESSUREPLATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_PRESSUREPLATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_PRESSUREPLATE.get())
                .add(JMWCBlocks.BLACK_ABORA_PRESSUREPLATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_PRESSUREPLATE.get());

        tag(BlockTags.SAPLINGS)
                .add(JMWCBlocks.AGRABAH_CEDAR_SAPLING.get())
                .add(JMWCBlocks.ALLMEN_OAK_SAPLING.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_SAPLING.get())
                .add(JMWCBlocks.BLACK_ABORA_SAPLING.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_SAPLING.get());

        tag(BlockTags.SLABS)
                .add(JMWCBlocks.AGRABAH_CEDAR_SLAB.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG_SLAB.get())
                .add(JMWCBlocks.ALLMEN_OAK_SLAB.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_SLAB.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.BLACK_ABORA_SLAB.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG_SLAB.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_SLAB.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG_SLAB.get());

        tag(BlockTags.STAIRS)
                .add(JMWCBlocks.AGRABAH_CEDAR_STAIRS.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG_STAIRS.get())
                .add(JMWCBlocks.ALLMEN_OAK_STAIRS.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_STAIRS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.BLACK_ABORA_STAIRS.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG_STAIRS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_STAIRS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG_STAIRS.get());

        tag(BlockTags.TRAPDOORS)
                .add(JMWCBlocks.AGRABAH_CEDAR_TRAPDOOR.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_TRAPDOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_TRAPDOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_TRAPDOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_TRAPDOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_TRAPDOOR.get());

        tag(BlockTags.WOODEN_BUTTONS)
                .add(JMWCBlocks.AGRABAH_CEDAR_BUTTON.get())
                .add(JMWCBlocks.ALLMEN_OAK_BUTTON.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_BUTTON.get())
                .add(JMWCBlocks.BLACK_ABORA_BUTTON.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_BUTTON.get());

        tag(BlockTags.WOODEN_DOORS)
                .add(JMWCBlocks.AGRABAH_CEDAR_DOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_DOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_DOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_DOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_DOOR.get());

        tag(BlockTags.WOODEN_FENCES)
                .add(JMWCBlocks.AGRABAH_CEDAR_FENCE.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_FENCE.get())
                .add(JMWCBlocks.ALLMEN_OAK_FENCE.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_FENCE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_FENCE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_FENCE.get())
                .add(JMWCBlocks.BLACK_ABORA_FENCE.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_FENCE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_FENCE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_FENCE.get());

        tag(BlockTags.WOODEN_SLABS)
                .add(JMWCBlocks.AGRABAH_CEDAR_SLAB.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG_SLAB.get())
                .add(JMWCBlocks.ALLMEN_OAK_SLAB.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_SLAB.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG_SLAB.get())
                .add(JMWCBlocks.BLACK_ABORA_SLAB.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG_SLAB.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_SLAB.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_SLAB.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG_SLAB.get());

        tag(BlockTags.WOODEN_STAIRS)
                .add(JMWCBlocks.AGRABAH_CEDAR_STAIRS.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_AGRABAH_CEDAR_LOG_STAIRS.get())
                .add(JMWCBlocks.ALLMEN_OAK_STAIRS.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_ALLMEN_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_STAIRS.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_AUDRAFLORA_OAK_LOG_STAIRS.get())
                .add(JMWCBlocks.BLACK_ABORA_STAIRS.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_BLACK_ABORA_LOG_STAIRS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_STAIRS.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_STAIRS.get())
                .add(JMWCBlocks.STRIPPED_CARAVAN_OLIVEWOOD_LOG_STAIRS.get());

        tag(BlockTags.WOODEN_PRESSURE_PLATES)
                .add(JMWCBlocks.AGRABAH_CEDAR_PRESSUREPLATE.get())
                .add(JMWCBlocks.ALLMEN_OAK_PRESSUREPLATE.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_PRESSUREPLATE.get())
                .add(JMWCBlocks.BLACK_ABORA_PRESSUREPLATE.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_PRESSUREPLATE.get());

        tag(BlockTags.WOODEN_TRAPDOORS)
                .add(JMWCBlocks.AGRABAH_CEDAR_TRAPDOOR.get())
                .add(JMWCBlocks.AGRABAH_CEDAR_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_TRAPDOOR.get())
                .add(JMWCBlocks.ALLMEN_OAK_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_TRAPDOOR.get())
                .add(JMWCBlocks.AUDRAFLORA_OAK_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_TRAPDOOR.get())
                .add(JMWCBlocks.BLACK_ABORA_LOG_TRAPDOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_TRAPDOOR.get())
                .add(JMWCBlocks.CARAVAN_OLIVEWOOD_LOG_TRAPDOOR.get());

    }
}